const PROJECTS = [
  {
    slug: "sae-reseau-multi-site",
    title_fr: "SAE réseau multi-site",
    title_en: "Multi-site network SAE",
    category: "SAE",
    short_fr: "Projet académique en cours de structuration. La fiche complète sera publiée après validation finale.",
    short_en: "Academic project currently being structured. The full technical sheet will be published after final validation.",
    description_fr: "Projet de formation orienté architecture réseau inter-sites. Le contenu public reste volontairement synthétique à ce stade.",
    description_en: "Training project focused on inter-site network architecture. Public content remains intentionally concise at this stage.",
    technologies: ["VLAN", "Routage", "Packet Tracer"],
    keyPoints_fr: ["Plan d'adressage", "Segmentation", "Documentation progressive"],
    keyPoints_en: ["Addressing plan", "Segmentation", "Progressive documentation"],
    result_fr: "Base technique en progression.",
    result_en: "Technical baseline in progress.",
    nextStep_fr: "Publier la version détaillée après consolidation.",
    nextStep_en: "Publish full details after consolidation.",
    link: "",
    image: ""
  },
  {
    slug: "scripts-powershell-atera",
    title_fr: "Scripts PowerShell Atera",
    title_en: "Atera PowerShell scripts",
    category: "Scripts",
    short_fr: "Base d'automatisation en cours de développement pour standardiser les tâches récurrentes.",
    short_en: "Automation baseline under development to standardize recurring tasks.",
    description_fr: "Série de scripts simples pour structurer des interventions de support de manière reproductible.",
    description_en: "Set of simple scripts used to structure support tasks in a repeatable way.",
    technologies: ["PowerShell", "Windows", "Atera"],
    keyPoints_fr: ["Lisibilité", "Réutilisabilité", "Tests progressifs"],
    keyPoints_en: ["Readability", "Reusability", "Progressive tests"],
    result_fr: "Première base exploitable en amélioration continue.",
    result_en: "First usable baseline under continuous improvement.",
    nextStep_fr: "Ajouter versionnement et guide d'usage.",
    nextStep_en: "Add versioning and usage guide.",
    link: "",
    image: ""
  },
  {
    slug: "serveur-dns-raspberry-pi",
    title_fr: "Serveur DNS sur Raspberry Pi",
    title_en: "Raspberry Pi DNS server",
    category: "Système",
    short_fr: "Lab personnel de pratique système/réseau actuellement en phase d'approfondissement.",
    short_en: "Personal system/network lab currently in an improvement phase.",
    description_fr: "Laboratoire personnel pour pratiquer l'installation et la maintenance d'un service DNS.",
    description_en: "Personal lab used to practice DNS service deployment and maintenance.",
    technologies: ["Linux", "Raspberry Pi", "DNS", "SSH"],
    keyPoints_fr: ["Environnement local", "Configuration de service", "Bases système"],
    keyPoints_en: ["Local environment", "Service configuration", "System fundamentals"],
    result_fr: "Plateforme de test fonctionnelle.",
    result_en: "Functional testing platform.",
    nextStep_fr: "Documenter architecture et résultats de tests.",
    nextStep_en: "Document architecture and test outcomes.",
    link: "",
    image: ""
  }
];
